services:
  sms:
    build:
      context: .
      dockerfile: Dockerfile
    image: peetahdarius/outsource-sms
    ports:
      - 5000:5000
    depends_on:
      - smsdb

  smsdb:
    image: postgres:15
    container_name: smsdb
    environment:
      POSTGRES_DB: sms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smspass
    ports:
      - "5432:5432"
    volumes:
      - sms_data:/var/lib/postgresql/data

volumes:
  sms_data: