services:
  client-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: peetahdarius/outsource-client-backend
    ports:
      - 5000:5000
    env_file:
      - .env 
    depends_on:
      - client-db

  
  client-db:
    image: mysql:8.0
    container_name: client-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ClientBackend!
      MYSQL_DATABASE: clientdb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: