"""initial commit

Revision ID: 2381e2930f84
Revises: 
Create Date: 2025-02-08 16:31:19.742993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2381e2930f84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('sender_id', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=254), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms')
    op.drop_table('credentials')
    # ### end Alembic commands ###
