services:
  email:
    build:
      context: .
      dockerfile: Dockerfile
    image: peetahdarius/outsource-email
    ports:
      - 8000:8000
    env_file:
      - .env 
    restart: always
    depends_on:
      emaildb:
        condition: service_healthy


  emaildb:
    image: postgres:15
    container_name: emaildb
    environment:
      POSTGRES_DB: email
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emailpass
    ports:
      - "5432:5432"
    volumes:
      - email_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "email"]
      interval: 5s
      retries: 5

volumes:
  email_data: