apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  SCHEDULE_DATABASE_USERNAME: postgres
  SCHEDULE_DATABASE_HOST: scheduledb
  SCHEDULE_DATABASE_PORT: "5432"
  SCHEDULE_DATABASE_NAME: schedule
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: admin
  