"""initial commit

Revision ID: fd20ed39ff1e
Revises: 
Create Date: 2025-02-18 22:58:48.744378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd20ed39ff1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('quotation_id', sa.String(length=200), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.Column('engineers', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
