"""added prefix

Revision ID: 154ca86743ba
Revises: ec2cd7cc29a9
Create Date: 2025-02-17 07:43:21.889799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154ca86743ba'
down_revision = 'ec2cd7cc29a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###
