"""changed engineer-task-id type to str

Revision ID: b11ddfa776ae
Revises: 4328f3d0f7b8
Create Date: 2025-02-24 01:39:20.779956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11ddfa776ae'
down_revision = '4328f3d0f7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disburse', schema=None) as batch_op:
        batch_op.alter_column('engineer_task_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disburse', schema=None) as batch_op:
        batch_op.alter_column('engineer_task_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
