"""changed taskid to task_id

Revision ID: b54bbf95e310
Revises: b11ddfa776ae
Create Date: 2025-02-24 01:41:26.800909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54bbf95e310'
down_revision = 'b11ddfa776ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disburse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Text(), nullable=True))
        batch_op.drop_column('taskid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disburse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taskid', sa.TEXT(), nullable=True))
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
