# Generated by Django 5.1.6 on 2025-02-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_code',
            field=models.CharField(default='254', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_code',
            field=models.CharField(default='3452', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='2974', max_length=4),
        ),
    ]
