# Generated by Django 5.1.6 on 2025-02-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_country_code_product_manufacturer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
