services:
  
  kong:
    image: kong:3.3.0  # or any recent version you prefer
    container_name: kong
    restart: unless-stopped
    environment:
      # Use DB-less mode so that Kong loads its configuration from a file
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml:ro
    ports:
      - "8000:8000"  # Proxy port
      - "8443:8443"  # Proxy SSL port
      - "8001:8001"  # Admin API port
      - "8444:8444"  # Admin API SSL port