"""initial commit

Revision ID: 5cc8e1040698
Revises: 
Create Date: 2025-02-11 22:40:44.890051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc8e1040698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c2_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_id', sa.String(length=200), nullable=True),
    sa.Column('trans_time', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('msisdn', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('middle_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('org_acc_balance', sa.Float(), nullable=True),
    sa.Column('bill_ref_number', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_key', sa.Text(), nullable=True),
    sa.Column('consumer_secret', sa.Text(), nullable=True),
    sa.Column('confirmation_url', sa.Text(), nullable=True),
    sa.Column('validation_url', sa.Text(), nullable=True),
    sa.Column('short_code', sa.String(length=50), nullable=True),
    sa.Column('command_id', sa.Text(), nullable=True),
    sa.Column('custom_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credentials')
    op.drop_table('c2_b')
    # ### end Alembic commands ###
